In [1]:
import numpy as np

In [2]:
#FONTOS!!!

# CSAK OTT LEHET HASZNÁLNI FOR LOOP-OT AHOL A FELADAT KÜLÖN KÉRI!
# [1,2,3,4] --> ezek az értékek np.array-ek. Ahol listát kérek paraméterként ott külön ki fogom emelni!
# Ha végeztél a feladatokkal, akkor notebook-ot alakítsd át .py.
# A FÁJLBAN CSAK A FÜGGVÉNYEK LEGYENEK! (KOMMENTEK MARADHATNAK)

In [3]:
#Készíts egy függvényt ami létre hoz egy nullákkal teli numpy array-t.
#Paraméterei: mérete (tuple-ként), default mérete pedig legyen egy (2,2)
#Be: (2,2)
#Ki: [[0,0],[0,0]]
#create_array()

In [4]:
def create_array(size = (2,2)) -> np.array:
    my_array = np.zeros(size)
    return my_array

create_array(size = (2,2))

array([[0., 0.],
       [0., 0.]])

In [5]:
#Készíts egy függvényt ami a paraméterként kapott array-t főátlóját feltölti egyesekkel
#Be: [[1,2],[3,4]]
#Ki: [[1,2],[3,1]]
#set_one()

In [20]:
def set_one(inpt: np.array):
    np.fill_diagonal(inpt, 1)

t = np.array([[1,2],[3,4]])
set_one(t)

In [21]:
# Készíts egy függvényt ami transzponálja a paraméterül kapott mártix-ot:
# Be: [[1, 2], [3, 4]]
# Ki: [[1, 2], [3, 4]]
# do_transpose()

In [23]:
def do_transpose(array: np.array) -> np.array:
    return np.transpose(array)

do_transpose([[1, 2], [3, 4]])

array([[1, 3],
       [2, 4]])

In [9]:
# Készíts egy olyan függvényt ami az array-ben lévő értékeket N tizenedjegyik kerekíti, ha nincs megadva ez a paraméter, akkor legyen az alapértelmezett a kettő 
# Be: [0.1223, 0.1675], 2
# Ki: [0.12, 0.17]
# round_array()

In [28]:
def round_array(array: np.array, rnd: int = 2) -> np.array:
    return np.around(array, rnd)

round_array(np.array([0.1223, 0.1675]), 2)

array([0.12, 0.17])

In [11]:
# Készíts egy olyan függvényt, ami a bementként kapott 0 és 1 ből álló tömben a 0 - False-ra, az 1 True-ra cserélni
# Be: [[1, 0, 0], [1, 1, 1],[0, 0, 0]]
# Ki: [[ True False False], [ True  True  True], [False False False]]
# bool_array()

In [17]:
def bool_array(matrix: np.array) -> np.array:

    return matrix.astype(bool)

bool_array(np.array([[1, 0, 0], [1, 1, 1],[0, 0, 0]]))

array([[ True, False, False],
       [ True,  True,  True],
       [False, False, False]])

In [ ]:
# Készíts egy olyan függvényt, ami a bementként kapott 0 és 1 ből álló tömben a 1 - False-ra az 0 True-ra cserélni
# Be: [[1, 0, 0], [1, 1, 1],[0, 0, 0]]
# Ki: [[ True False False], [ True  True  True], [False False False]]
# invert_bool_array()

In [ ]:
def invert_bool_array(matrix: np.array) -> np.array:
    return np.invert(matrix.astype(bool))

In [ ]:
# Készíts egy olyan függvényt ami a paraméterként kapott array-t kilapítja
# Be: [[1,2], [3,4]]
# Ki: [1,2,3,4]
# flatten()


In [19]:
def flatten(array: np.array) -> np.array:
    return array.flatten()

flatten(np.array([[1,2], [3,4]]))

array([1, 2, 3, 4])